language: java
jdk: openjdk8
install: true

cache:
  directories:
    - $HOME/.m2

script:
  - mvn -B verify && cd ..

notifications:
  email:
    recipients:
      - egnaf@yahoo.com
    on_success: never
    on_failure: always
