server:
  port: 8065
  servlet:
    context-path: /auth/0.1

spring:
  profiles:
    active: dev
  data:
    mongodb:
#      uri: mongodb://localhost:27017/auth-db
      uri: mongodb+srv://admin:pass1234@cluster0-dpp5v.mongodb.net/test?retryWrites=true&w=majority
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: egnaf
    password: 151196Zc!$@#yahoo
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls: # TLS , port 587
            enable: true
            required: true

security:
  token:
    secret: "secret"
    expire: 3600000
    type: "bearer"

dozer:
  cache:
    converter-by-dest-type-maxsize: 5000
    super-type-maxsize: 5000
